- name: install java server on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: latest
        update_cache : true
    - name: wget the file
      ansible.builtin.get_url:
        dest: /tmp 
        url: https://download.java.net/java/GA/jdk17.0.1/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-17.0.1_linux-x64_bin.tar.gz
    - name: make directory
      ansible.builtin.file:
        path: /usr/java
        state: directory
    - name: copy the file 
      ansible.builtin.copy:
        dest: /usr/java
        src: /tmp
        remote_src: true
    - name: extract tar file 
      ansible.builtin.unarchive:
        dest: /usr/java
        src: /tmp/openjdk-17.0.1_linux-x64_bin.tar.gz
        remote_src: true
    - name: edit the data in /etc/profile
      ansible.builtin.blockinfile:
        block: 
          # Java 17
          JAVA_HOME=/usr/java/jdk-17.0.1
          PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
          export JAVA_HOME
          export PATH
        path: /etc/profile
    - name: command in line 
      ansible.builtin.command: sudo update-alternatives --install "/usr/bin/java" "java" "/usr/java/jdk-17.0.1/bin/java" 1
    - name: command in line 
      ansible.builtin.command: sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/java/jdk-17.0.1/bin/javac" 1